#!/bin/sh
echo "Starting Ktlint"

# Run Ktlint to check for code style errors
./gradlew ktlintCheck
# Capture the exit code of the previous command
Exit_code=$?
# Check if Ktlint found errors
if [ $Exit_code -ne 0 ]; then
    echo "Ktlint found errors. Commit aborted."
    exit 1
fi
echo "Starting Unit testing"
./gradlew test
# Capture the exit code of the previous command
test_exit_code=$?
# Check if Ktlint found errors
if [ $test_exit_code -ne 0 ]; then
    echo "Test Errors. Commit aborted"
    exit 1
fi
# If no errors were found, allow the commit
exit 0

