#!/bin/sh

# Check for code style violations with ktlint
echo "Running git pre-commit hook"
./gradlew ktlintFormat
STATUS=$?
# return 1 exit code if running checks fails
[ $STATUS -ne 0 ] && exit 1
exit 0